/* AUTO-GENERATED QEMU repro source (temporary) — MultiAgent */
static const char SELMIN_SRC[] =
"/* AIPL -> C  (--xinu-jit: self-contained integer subset for /compile) */\n"
"struct Obj { int cls; int f[1]; };\n"
"struct Obj g_obj[64];\n"
"int g_nobj;\n"
"\n"
"int g_spawn(int cls) {\n"
"  int id; id = cc_actor_new();\n"
"  if (id < 0) { return -1; }\n"
"  g_nobj = g_nobj + 1;\n"
"  g_obj[id].cls = cls;\n"
"  if (cls == 0) {\n"
"  }\n"
"  if (cls == 1) {\n"
"  }\n"
"  return id;\n"
"}\n"
"\n"
"int m_Agent_ask(int self, int a0, int a1, int a2, int a3) {\n"
"  int v_director = a0;\n"
"  int v_topic = a1;\n"
"  int v_fragment = cc_llm(v_topic);\n"
"  enqueue(v_int_of(v_director), 2, v_fragment, v_int(0), v_int(0), v_int(0));\n"
"  return 0;\n"
"}\n"
"\n"
"int m_Director_run(int self, int a0, int a1, int a2, int a3) {\n"
"  int v_a1 = v_int(g_spawn(0));\n"
"  int v_a2 = v_int(g_spawn(0));\n"
"  enqueue(v_int_of(v_a1), 0, v_int(self), v_str(\"The brave knight\"), v_int(0), v_int(0));\n"
"  enqueue(v_int_of(v_a2), 0, v_int(self), v_str(\"The sleepy dragon\"), v_int(0), v_int(0));\n"
"  int v_got = v_int(0);\n"
"  while (v_truthy(v_lt(v_got, v_int(2)))) {\n"
"    { int __sm = cc_select(self, 1, 2, -1, -1, -1);\n"
"      if (__sm == 2) {\n"
"        int v_x = cc_sel_arg(0);\n"
"        v_print(v_add(v_str(\"agent: \"), v_x));\n"
"        v_got = v_add(v_got, v_int(1));\n"
"      }\n"
"    }\n"
"  }\n"
"  v_print(v_str(\"director: collected 2 fragments\"));\n"
"  return 0;\n"
"}\n"
"\n"
"int dispatch(int self, int meth, int a0, int a1, int a2, int a3) {\n"
"  int c; c = g_obj[self].cls;\n"
"  if (c == 0) {\n"
"    if (meth == 0) return m_Agent_ask(self, a0, a1, a2, a3);\n"
"  }\n"
"  if (c == 1) {\n"
"    if (meth == 1) return m_Director_run(self, a0, a1, a2, a3);\n"
"  }\n"
"  return 0;\n"
"}\n"
"\n"
"int __method_id(int name) {\n"
"  if (v_truthy(v_eq(name, v_str(\"ask\")))) return v_int(0);\n"
"  if (v_truthy(v_eq(name, v_str(\"run\")))) return v_int(1);\n"
"  if (v_truthy(v_eq(name, v_str(\"reply\")))) return v_int(2);\n"
"  return v_int(-1);\n"
"}\n"
"\n"
"int __nobj() { return v_int(g_nobj); }\n"
"\n"
"int main() {\n"
"  int v_d = v_int(g_spawn(1));\n"
"  enqueue(v_int_of(v_d), 1, v_int(0), v_int(0), v_int(0), v_int(0));\n"
"  return 0;\n"
"}\n"
"";
